name: react-native-android-build-apk
on:
  push:
jobs:
  build-android:
    runs-on: windows-latest
    steps: 
      - name: Build Android Release
        run: |
          C:
          dir
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release-unsigned.apk
          path: D:/CheckChequer/app/build/outputs/apk/release/
          
          
