name: react-native-android-build-apk
on:
  push:
jobs:
  install-and-test:
    runs-on:  self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: self-hosted
    steps: 
      - name: Build Android Release
        run: |
          chmod +x ./gradlew
          cd D:/CheckChequer && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: D:/CheckChequer/app/build/outputs/apk/debug/
          
