name: AndroidCI
on:
  push:
jobs:
  build-android:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v2
      - name: findFoldar
        run: |
          D:
          cd D:\a\CheckChequer\CheckChequer
          
      - name: Build
      - run: ./gradlew build
      
      - name: UnitTests
      - run: ./gradlew testReleaseUnitTest
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: D:\a\CheckChequer\CheckChequer/app/build/outputs/apk/debug/
